title: "Kenneth Fond"
author: "Kenneth Fond"
description: "Made with Jekyll and GitHub Pages"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true 
show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://kenf1.github.io/", title: "Homepage"}
  - {file: "index.md"}
  - {file: "brief_cv.md"}
  - {file: "about_me.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:"}
  - {title: Github, icon: github, url: "https://github.com/kenf1"}
  - {title: Twitter, icon: twitter, url: ""}

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
 - jekyll-remote-theme
 - jekyll-feed
